name: SaveSolar
favicon: null
layout_spectrum: 0.90853
typography_spectrum: 0.86412
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2bbff0'
    - '#00ffff'
    - '#0080ff'
    - '#0000ff'
    - '#000000'
  brandStrength: 0.25
  lightness: 0.005302512785419822
  saturation: 0.5270265843719244
  rhythmicContrast: 0
purpose: []
